#version: "3.3"
#services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#    - target: 80
#      published: 80
#      protocol: tcp
#    volumes:
#    - type: bind
#      source: ./nginx/nginx.conf
#      target: /etc/nginx/nginx.conf
#  mysql:
#    image: mysql
#    build: ./db
#    container_name: mysql
#  books:
#    build: .
#    container_name: books

version: "3.3"
services:
  mysql:
    image: db
    build: ./db
    container_name: mysql
  books:
    build: .
    image: books
    deploy: 
      replicas: 10
    ports:
    - published: 5000
      target: 5000


